// <auto-generated />
using HappyHackers_DRRIC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HappyHackers_DRRIC.Migrations
{
    [DbContext(typeof(BadReportsContext))]
    [Migration("20210307220105_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HappyHackers_DRRIC.Models.BadReports", b =>
                {
                    b.Property<string>("uid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CoinAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DOB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("uid");

                    b.ToTable("BadReport");

                    b.HasData(
                        new
                        {
                            uid = "113177321",
                            CoinAddress = "rwU8rAiE2eyEPz3sikfbHuqCuiAtdXqa2v",
                            DOB = "10/17/1994",
                            FirstName = "Zac",
                            Hash = "i9zzz3zz0m37mzi90704330990mz99443b2z03b7z7220073bi49b7m0z347b923",
                            IPAddress = "192.0.7.8",
                            LastName = "Wellmer"
                        },
                        new
                        {
                            uid = "107672511",
                            CoinAddress = "r3mZvvHVLPtRWAujzBsAoXqH11jhwQZvzY",
                            DOB = "3/2/1971",
                            FirstName = "Anabel",
                            Hash = "24ii22zz44432i9260b26960i393b69007z6z737b0224074z209940399zz9973",
                            IPAddress = "192.0.6.1",
                            LastName = "Asare"
                        },
                        new
                        {
                            uid = "106820062",
                            CoinAddress = "rNwgkFj6QadEXUyS1jgTD2XEsi8HanKzDX",
                            DOB = "9/4/1974",
                            FirstName = "Jess",
                            Hash = "00063zmmz667293973327002i7307779707mb977b0i9z9b4ib3bz77mb33zm3i3",
                            IPAddress = "192.0.2.1",
                            LastName = "Mann"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
