// <auto-generated />
using HappyHackers_DRRIC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HappyHackers_DRRIC.Migrations
{
    [DbContext(typeof(BadReportsContext))]
    [Migration("20210310045245_AddingPostingLicensee")]
    partial class AddingPostingLicensee
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HappyHackers_DRRIC.Models.BadReports", b =>
                {
                    b.Property<string>("uid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CoinAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CryptocurrencyCurrencyID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CurrencyID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DOB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostingLicenseeLicenseeID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("uid");

                    b.HasIndex("CategoryID");

                    b.HasIndex("CryptocurrencyCurrencyID");

                    b.HasIndex("PostingLicenseeLicenseeID");

                    b.ToTable("BadReport");

                    b.HasData(
                        new
                        {
                            uid = "113177321",
                            CoinAddress = "rwU8rAiE2eyEPz3sikfbHuqCuiAtdXqa2v",
                            CurrencyID = "X2",
                            DOB = "10/17/1994",
                            FirstName = "Zac",
                            Hash = "i9zzz3zz0m37mzi90704330990mz99443b2z03b7z7220073bi49b7m0z347b923",
                            IPAddress = "192.0.7.8",
                            LastName = "Wellmer",
                            LicenseeID = "Coin01"
                        },
                        new
                        {
                            uid = "107672511",
                            CoinAddress = "r3mZvvHVLPtRWAujzBsAoXqH11jhwQZvzY",
                            CurrencyID = "X2",
                            DOB = "3/2/1971",
                            FirstName = "Anabel",
                            Hash = "24ii22zz44432i9260b26960i393b69007z6z737b0224074z209940399zz9973",
                            IPAddress = "192.0.6.1",
                            LastName = "Asare",
                            LicenseeID = "Gem02"
                        },
                        new
                        {
                            uid = "106820062",
                            CoinAddress = "rNwgkFj6QadEXUyS1jgTD2XEsi8HanKzDX",
                            CurrencyID = "X2",
                            DOB = "9/4/1974",
                            FirstName = "Jess",
                            Hash = "00063zmmz667293973327002i7307779707mb977b0i9z9b4ib3bz77mb33zm3i3",
                            IPAddress = "192.0.2.1",
                            LastName = "Mann",
                            LicenseeID = "Pax03"
                        });
                });

            modelBuilder.Entity("HappyHackers_DRRIC.Models.Category", b =>
                {
                    b.Property<string>("CategoryID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Crime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryID = "CE1",
                            Crime = "Child Explotation"
                        },
                        new
                        {
                            CategoryID = "HT1",
                            Crime = "Human Tracking"
                        },
                        new
                        {
                            CategoryID = "TF1",
                            Crime = "Terror Financing"
                        });
                });

            modelBuilder.Entity("HappyHackers_DRRIC.Models.Cryptocurrency", b =>
                {
                    b.Property<string>("CurrencyID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CurrencyID");

                    b.ToTable("Cryptocurrency");

                    b.HasData(
                        new
                        {
                            CurrencyID = "E1",
                            Code = "ETH"
                        },
                        new
                        {
                            CurrencyID = "X2",
                            Code = "XRP"
                        },
                        new
                        {
                            CurrencyID = "B3",
                            Code = "BTC"
                        });
                });

            modelBuilder.Entity("HappyHackers_DRRIC.Models.PostingLicensee", b =>
                {
                    b.Property<string>("LicenseeID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LicenseeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LicenseeID");

                    b.ToTable("PostingLicensee");

                    b.HasData(
                        new
                        {
                            LicenseeID = "Coin01",
                            LicenseeName = "Coinbase"
                        },
                        new
                        {
                            LicenseeID = "Gem02",
                            LicenseeName = "Gemini"
                        },
                        new
                        {
                            LicenseeID = "Pax03",
                            LicenseeName = "Paxos"
                        });
                });

            modelBuilder.Entity("HappyHackers_DRRIC.Models.BadReports", b =>
                {
                    b.HasOne("HappyHackers_DRRIC.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID");

                    b.HasOne("HappyHackers_DRRIC.Models.Cryptocurrency", "Cryptocurrency")
                        .WithMany()
                        .HasForeignKey("CryptocurrencyCurrencyID");

                    b.HasOne("HappyHackers_DRRIC.Models.PostingLicensee", "PostingLicensee")
                        .WithMany()
                        .HasForeignKey("PostingLicenseeLicenseeID");

                    b.Navigation("Category");

                    b.Navigation("Cryptocurrency");

                    b.Navigation("PostingLicensee");
                });
#pragma warning restore 612, 618
        }
    }
}
